import React from 'react';
import {
  AccountBalance,
  AccountBalanceWallet,
  AllInbox,
  ChildFriendly,
  Cake,
  DirectionsBike,
  DriveEta,
  EmojiSymbols,
  Fastfood,
  Favorite,
  FitnessCenter,
  Kitchen,
  LocalDining,
  MenuBook,
  Pets,
  PlayForWork,
  School,
  ShoppingCart,
  Waves,
  WorkOutline,
} from '@material-ui/icons';

export const icons = [
  <AccountBalance />,
  <AccountBalanceWallet />,
  <AllInbox />,
  <ChildFriendly />,
  <Cake />,
  <DirectionsBike />,
  <DriveEta />,
  <EmojiSymbols />,
  <Fastfood />,
  <Favorite />,
  <FitnessCenter />,
  <Kitchen />,
  <LocalDining />,
  <MenuBook />,
  <Pets />,
  <PlayForWork />,
  <School />,
  <ShoppingCart />,
  <Waves />,
  <WorkOutline />,
];

export default (state = icons, _) => state;
